Apply One-hot encoding for cities + regions
anasneji2002/Housing_pricing pull request #32
Opened 2024-12-12 19:11 UTC by anasneji2002

### **What to Expect ?**

This PR aims to do the following 
 - Encode the cities
 - Encode the regions

This will be done by creating 2 maps that will be stored as jsons for future references
 - one for cities encoding
 - one for regions encoding

And replacing the string values by their encodings

On a side note i noticed few bugs caused by this PR #31 so I went ahead and fixed them in mine
Also there are other tasks to do as well like removing duplicate columns but it will be done later on

2024-12-15 20:07 UTC, neirezcher requested changes
I propose using an alternative encoding system that reflects the price ranges of cities, instead of the one provided in this PR. After conducting research, I have categorized cities based on their average price per square meter as follows:

**Estimated Average Prices by Zone**

- **Premium Zones**

Lac 1 / Lac 2: 4,000 - 6,500 TND/m²
Jardins de Carthage: 3,500 - 5,500 TND/m²
Gammarth: 3,500 - 5,000 TND/m²
Sidi Bou Saïd: 4,500 - 7,000 TND/m²
Carthage: 3,500 - 6,000 TND/m²
Marsa (Ain Zaghouan Nord / Sud, Sidi Daoud): 3,000 - 5,000 TND/m²

**- High-End Residential Zones**

Ennasr 1 & 2: 2,500 - 3,500 TND/m²
Menzah 5, 6, 7, 8, 9: 2,200 - 3,800 TND/m²
Riadh Andalous: 2,200 - 3,200 TND/m²
Chotrana (1, 2, 3): 2,500 - 3,500 TND/m²
Ariana Ville: 2,200 - 3,200 TND/m²
Mutuelleville: 2,500 - 3,800 TND/m²

- **Medium Zones**

La Soukra: 1,800 - 2,800 TND/m²
Ain Zaghouan: 1,800 - 2,700 TND/m²
Menzah 1, 2: 1,800 - 2,800 TND/m²
Centre Urbain Nord: 2,500 - 3,200 TND/m²
Ariana Essoughra: 1,500 - 2,200 TND/m²

- **Popular Zones**

Ben Arous / Hammam Lif / Hammam Chott: 1,200 - 1,800 TND/m²
Mourouj (1 to 6): 1,200 - 1,800 TND/m²
Ettadhamen / Douar Hicher: 900 - 1,400 TND/m²
Manouba / Denden / Oued Ellil: 900 - 1,500 TND/m²
Mégrine: 1,200 - 1,800 TND/m²
Ezzahra / Rades: 1,500 - 2,000 TND/m²
Tebourba / Kalaat Landalous / Mornaguia: 800 - 1,300 TND/m²
Historic / Central Zones
Médina (Bab Bhar, Bab Souika, Sidi El Bechir): 800 - 1,400 TND/m²
Lafayette / Tunis Belvédère: 2,000 - 3,200 TND/m²
Omrane Supérieur / El Omrane: 1,000 - 1,800 TND/m²
Monfleury / Kabaria: 800 - 1,300 TND/m²

**- Developing Zones**

Fouchana / Mohamedia: 800 - 1,300 TND/m²
Boumhel / Boumhel El Bassatine: 1,000 - 1,800 TND/m²
Mnihla / Ettahrir: 900 - 1,400 TND/m²
Proposed Encoding System
The cities can be divided into tiers based on these price ranges:

Premium: Above 3,500 TND/m² → Encoding: 1
High: 2,500 - 3,500 TND/m² → Encoding: 2
Medium: 1,500 - 2,500 TND/m² → Encoding: 3
Low: Below 1,500 TND/m² → Encoding: 4

2024-12-15 20:23 UTC, anasneji2002 commented on notebooks/cities_encoding.ipynb
1- I would like to propose an alternative to this : instead of sorting the cities alphabetically we sort them by average price , that way the locality is still correlated to the price (also i'm strongly against the idea of categorizing the localities because simply we are not in classification context plus with ur suggestion we would garantee that at least 8 cities would have the same encoding / value which I disagree with . for example Lac1/2 and jardins de carthages shouldn't have the same rating provided that they don't cost the same)
2- will remove it
3- In our specific case deleting those rows won't have any impact (2 out of 6k+ isn't really that important)

2025-01-04 20:58 UTC, anasneji2002 commented on notebooks/cities_encoding.ipynb
@neirezcher updated the encoding to take into account the pricing in the area

2025-01-16 10:44 UTC, neirezcher approved these changes
Everything looks good to me! 👍 However, I suggest removing the 'gouvernate' columns since we are only working with the Big Tunis city instances. Adding this extra dimensionality doesn’t provide any additional value and may only increase complexity.

2025-01-16 10:44 UTC, merged